<?php
/**
 * Loader CSS styles for cross-domain authentication
 */
?>
<style>
    .loading-mask {
        position: fixed;
        z-index: 9999;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(255, 255, 255, 0.7);
    }
    
    .loading-mask .loader {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
    
    .loading-mask .loader > img {
        width: 150px;
        height: 150px;
    }
</style>