<?php
/**
 * JavaScript initialization for cross-domain website switcher
 *
 * @var \TheDevKitchen\JwtCrossDomainAuth\Block\Switcher $block
 */
?>
<script type="text/x-magento-init">
{
    "[data-role=cross-domain-container]": {
        "crossDomainSwitch": {
            "tokenUrl": "<?= $block->getUrl('jwt/token') ?>",
            "crossDomainUrl": "<?= $block->getUrl('jwt/login') ?>"
        }
    }
}
</script>