<?php
/**
 * JavaScript initialization for cross-domain website switcher
 *
 * @var \TheDevKitchen\JwtCrossDomainAuth\Block\Switcher $block
 */
?>
<script type="text/x-magento-init">
{
    ".cross-domain-link": {
        "crossDomainSwitch": {
            "tokenUrl": "<?= $block->getUrl('crossdomain/token/index') ?>",
            "crossDomainUrl": "<?= $block->getUrl('crossdomain/login') ?>"
        }
    }
}
</script>